name: Build
on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}
      - name: Update Package Version from Tag
        if: github.ref_type == 'tag'
        uses: BellCubeDev/update-package-version-by-release-tag@v2
        with:
          version: ${{ github.ref_name }}
          keep-v: "false" # If set to "true", will not remove any 'v' prefix from the version number.
          ignore-semver-check: "false" # If set to "true", will not check if the version number is a valid semver version.
      - name: Run Build Pipeline
        uses: ./.github/actions/node-build
        with:
          package-token: ${{ secrets.PACKAGE_TOKEN }}
          node-version: "24"
          build-command: npm run build
          extra-command: npm run check:args && SETTINGS_CHANNEL=formal npm test && test -s dist/DualSubs.Universal.yaml
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: |
            CHANGELOG.md
            rulesets
            dist
