name: Dev
on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}
          ref: dev
      - name: Run Build Pipeline
        uses: ./.github/actions/node-build
        with:
          package-token: ${{ secrets.PACKAGE_TOKEN }}
          node-version: "24"
          build-command: npm run dev
          extra-command: npm run check:args && SETTINGS_CHANNEL=dev npm test && test -s dist/DualSubs.Universal.dev.yaml
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: |
            CHANGELOG.md
            rulesets
            dist
